/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    empresas: Empresa;
    funcionarios: Funcionario;
    'laudos-sst': LaudosSst;
    media: Media;
    'logs-auditoria': LogsAuditoria;
    'exames-medicos': ExamesMedico;
    notificacoes: Notificacoe;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    empresas: EmpresasSelect<false> | EmpresasSelect<true>;
    funcionarios: FuncionariosSelect<false> | FuncionariosSelect<true>;
    'laudos-sst': LaudosSstSelect<false> | LaudosSstSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'logs-auditoria': LogsAuditoriaSelect<false> | LogsAuditoriaSelect<true>;
    'exames-medicos': ExamesMedicosSelect<false> | ExamesMedicosSelect<true>;
    notificacoes: NotificacoesSelect<false> | NotificacoesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'user';
  empresa?: (number | null) | Empresa;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "empresas".
 */
export interface Empresa {
  id: number;
  cnpj: string;
  razaoSocial: string;
  tipo: 'privado' | 'publico';
  contato?: string | null;
  auditoria?: {
    usuario?: (number | null) | User;
    dataAlteracao?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "funcionarios".
 */
export interface Funcionario {
  id: number;
  cpf: string;
  nome: string;
  cargo: string;
  empresa: number | Empresa;
  setor: string;
  auditoria?: {
    usuario?: (number | null) | User;
    dataAlteracao?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "laudos-sst".
 */
export interface LaudosSst {
  id: number;
  empresa: number | Empresa;
  tipoLaudo: string;
  validade: string;
  arquivoPdf: number | Media;
  auditoria?: {
    usuario?: (number | null) | User;
    dataAlteracao?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  empresa?: (number | null) | Empresa;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logs-auditoria".
 */
export interface LogsAuditoria {
  id: number;
  quem?: (number | null) | User;
  onde: string;
  quando: string;
  valorAnterior?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  valorNovo?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  empresa?: (number | null) | Empresa;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exames-medicos".
 */
export interface ExamesMedico {
  id: number;
  funcionario: number | Funcionario;
  empresa: number | Empresa;
  tipoExame: 'admissional' | 'periodico' | 'retorno_trabalho' | 'mudanca_funcao' | 'demissional';
  dataExame: string;
  validade: string;
  status: 'apto' | 'inapto';
  crmMedico?: string | null;
  /**
   * Exemplo: RO, SP, RJ
   */
  ufMedico?: string | null;
  auditoria?: {
    usuario?: (number | null) | User;
    dataAlteracao?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notificacoes".
 */
export interface Notificacoe {
  id: number;
  empresa: number | Empresa;
  titulo: string;
  mensagem: string;
  lida: boolean;
  tipo: 'alerta' | 'info' | 'erro';
  auditoria?: {
    usuario?: (number | null) | User;
    dataAlteracao?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'empresas';
        value: number | Empresa;
      } | null)
    | ({
        relationTo: 'funcionarios';
        value: number | Funcionario;
      } | null)
    | ({
        relationTo: 'laudos-sst';
        value: number | LaudosSst;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'logs-auditoria';
        value: number | LogsAuditoria;
      } | null)
    | ({
        relationTo: 'exames-medicos';
        value: number | ExamesMedico;
      } | null)
    | ({
        relationTo: 'notificacoes';
        value: number | Notificacoe;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  empresa?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "empresas_select".
 */
export interface EmpresasSelect<T extends boolean = true> {
  cnpj?: T;
  razaoSocial?: T;
  tipo?: T;
  contato?: T;
  auditoria?:
    | T
    | {
        usuario?: T;
        dataAlteracao?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "funcionarios_select".
 */
export interface FuncionariosSelect<T extends boolean = true> {
  cpf?: T;
  nome?: T;
  cargo?: T;
  empresa?: T;
  setor?: T;
  auditoria?:
    | T
    | {
        usuario?: T;
        dataAlteracao?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "laudos-sst_select".
 */
export interface LaudosSstSelect<T extends boolean = true> {
  empresa?: T;
  tipoLaudo?: T;
  validade?: T;
  arquivoPdf?: T;
  auditoria?:
    | T
    | {
        usuario?: T;
        dataAlteracao?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  empresa?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logs-auditoria_select".
 */
export interface LogsAuditoriaSelect<T extends boolean = true> {
  quem?: T;
  onde?: T;
  quando?: T;
  valorAnterior?: T;
  valorNovo?: T;
  empresa?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exames-medicos_select".
 */
export interface ExamesMedicosSelect<T extends boolean = true> {
  funcionario?: T;
  empresa?: T;
  tipoExame?: T;
  dataExame?: T;
  validade?: T;
  status?: T;
  crmMedico?: T;
  ufMedico?: T;
  auditoria?:
    | T
    | {
        usuario?: T;
        dataAlteracao?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notificacoes_select".
 */
export interface NotificacoesSelect<T extends boolean = true> {
  empresa?: T;
  titulo?: T;
  mensagem?: T;
  lida?: T;
  tipo?: T;
  auditoria?:
    | T
    | {
        usuario?: T;
        dataAlteracao?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}